// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CommonResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
	Success bool        `json:"success"`
}

type Focus struct {
	Id    string `json:"id"`
	Title string `json:"title"`
	Image string `json:"image"`
	Link  string `json:"link"`
}

type FocusRequest struct {
	Id string `form:"id"` //Get传值
}
