// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddFocusRequest struct {
	Title string `form:"title"`
	Pic   string `form:"pic"`
	Link  string `form:"link"`
}

type AddUserRequest struct {
	Name string `form:"name"`
	Age  int    `form:"age,default=18"` //默认值
	Sex  int    `form:"sex,option=1|2"` //选项,枚举值
}

type Article struct {
	Id      int    `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type ArticleRequest struct {
	Id int `path:"id"` //动态路由
}

type CommonResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
	Success bool        `json:"success"`
}

type Focus struct {
	Id    int    `json:"id"`
	Title string `json:"title"`
	Pic   string `json:"pic"`
	Link  string `json:"link"`
}

type FocusRequest struct {
	Id int `form:"id"` //Get传值
}

type UpdateFocusRequest struct {
	Id    int    `form:"id"`
	Title string `form:"title"`
	Pic   string `form:"pic"`
	Link  string `form:"link"`
}

type UpdateUserRequest struct {
	Id   int    `json:"id"`
	Name string `form:"name"`
	Age  int    `form:"age,default=18"` //默认值
	Sex  int    `form:"sex,option=1|2"` //选项,枚举值
}

type UserRequest struct {
	Id int `json:"id"`
}
