// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"zerorequest/rpc/user/internal/logic"
	"zerorequest/rpc/user/internal/svc"
	___pb "zerorequest/rpc/user/proto/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	___pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) AddUser(ctx context.Context, in *___pb.UserMsg) (*___pb.Response, error) {
	l := logic.NewAddUserLogic(ctx, s.svcCtx)
	return l.AddUser(in)
}
