// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"zerorequest/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/addFocus",
				Handler: AddFocusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/addUser",
				Handler: AddUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/article/:id",
				Handler: GetArticleByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/deleteFocus",
				Handler: DeleteFocusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/focus",
				Handler: GetFocusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/oneFocus",
				Handler: GetFocusByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/updateFocus",
				Handler: UpdateFocusHandler(serverCtx),
			},
		},
	)
}
