// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/data_engine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DumpMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvPath       string                 `protobuf:"bytes,1,opt,name=csv_path,json=csvPath,proto3" json:"csv_path,omitempty"`
	DumpPath      string                 `protobuf:"bytes,2,opt,name=dump_path,json=dumpPath,proto3" json:"dump_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DumpMsg) Reset() {
	*x = DumpMsg{}
	mi := &file_proto_data_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DumpMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DumpMsg) ProtoMessage() {}

func (x *DumpMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DumpMsg.ProtoReflect.Descriptor instead.
func (*DumpMsg) Descriptor() ([]byte, []int) {
	return file_proto_data_engine_proto_rawDescGZIP(), []int{0}
}

func (x *DumpMsg) GetCsvPath() string {
	if x != nil {
		return x.CsvPath
	}
	return ""
}

func (x *DumpMsg) GetDumpPath() string {
	if x != nil {
		return x.DumpPath
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_data_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_data_engine_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ForwardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRequest) Reset() {
	*x = ForwardRequest{}
	mi := &file_proto_data_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRequest) ProtoMessage() {}

func (x *ForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRequest.ProtoReflect.Descriptor instead.
func (*ForwardRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_engine_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardRequest) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Status        uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Category      uint32                 `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	Stock         uint32                 `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Price         uint32                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Flags         uint32                 `protobuf:"varint,6,opt,name=flags,proto3" json:"flags,omitempty"`
	Tags          string                 `protobuf:"bytes,7,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_proto_data_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_engine_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardResponse) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ForwardResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ForwardResponse) GetCategory() uint32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *ForwardResponse) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ForwardResponse) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ForwardResponse) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *ForwardResponse) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type InvertedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvertedRequest) Reset() {
	*x = InvertedRequest{}
	mi := &file_proto_data_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvertedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvertedRequest) ProtoMessage() {}

func (x *InvertedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvertedRequest.ProtoReflect.Descriptor instead.
func (*InvertedRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_engine_proto_rawDescGZIP(), []int{4}
}

func (x *InvertedRequest) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type InvertedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []uint32               `protobuf:"varint,1,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvertedResponse) Reset() {
	*x = InvertedResponse{}
	mi := &file_proto_data_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvertedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvertedResponse) ProtoMessage() {}

func (x *InvertedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvertedResponse.ProtoReflect.Descriptor instead.
func (*InvertedResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_engine_proto_rawDescGZIP(), []int{5}
}

func (x *InvertedResponse) GetProductIds() []uint32 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

var File_proto_data_engine_proto protoreflect.FileDescriptor

const file_proto_data_engine_proto_rawDesc = "" +
	"\n" +
	"\x17proto/data_engine.proto\x12\x06engine\"A\n" +
	"\aDumpMsg\x12\x19\n" +
	"\bcsv_path\x18\x01 \x01(\tR\acsvPath\x12\x1b\n" +
	"\tdump_path\x18\x02 \x01(\tR\bdumpPath\",\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"/\n" +
	"\x0eForwardRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\"\xba\x01\n" +
	"\x0fForwardResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\rR\bcategory\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\rR\x05stock\x12\x14\n" +
	"\x05price\x18\x05 \x01(\rR\x05price\x12\x14\n" +
	"\x05flags\x18\x06 \x01(\rR\x05flags\x12\x12\n" +
	"\x04tags\x18\a \x01(\tR\x04tags\"0\n" +
	"\x0fInvertedRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\"3\n" +
	"\x10InvertedResponse\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\rR\n" +
	"productIds2\xe7\x02\n" +
	"\n" +
	"DataEngine\x123\n" +
	"\x0eForwardBuilder\x12\x0f.engine.DumpMsg\x1a\x10.engine.Response\x124\n" +
	"\x0fInvertedBuilder\x12\x0f.engine.DumpMsg\x1a\x10.engine.Response\x125\n" +
	"\x10LoadForwardIndex\x12\x0f.engine.DumpMsg\x1a\x10.engine.Response\x126\n" +
	"\x11LoadInvertedIndex\x12\x0f.engine.DumpMsg\x1a\x10.engine.Response\x12=\n" +
	"\n" +
	"GetForward\x12\x16.engine.ForwardRequest\x1a\x17.engine.ForwardResponse\x12@\n" +
	"\vGetInverted\x12\x17.engine.InvertedRequest\x1a\x18.engine.InvertedResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_data_engine_proto_rawDescOnce sync.Once
	file_proto_data_engine_proto_rawDescData []byte
)

func file_proto_data_engine_proto_rawDescGZIP() []byte {
	file_proto_data_engine_proto_rawDescOnce.Do(func() {
		file_proto_data_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_engine_proto_rawDesc), len(file_proto_data_engine_proto_rawDesc)))
	})
	return file_proto_data_engine_proto_rawDescData
}

var file_proto_data_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_data_engine_proto_goTypes = []any{
	(*DumpMsg)(nil),          // 0: engine.DumpMsg
	(*Response)(nil),         // 1: engine.Response
	(*ForwardRequest)(nil),   // 2: engine.ForwardRequest
	(*ForwardResponse)(nil),  // 3: engine.ForwardResponse
	(*InvertedRequest)(nil),  // 4: engine.InvertedRequest
	(*InvertedResponse)(nil), // 5: engine.InvertedResponse
}
var file_proto_data_engine_proto_depIdxs = []int32{
	0, // 0: engine.DataEngine.ForwardBuilder:input_type -> engine.DumpMsg
	0, // 1: engine.DataEngine.InvertedBuilder:input_type -> engine.DumpMsg
	0, // 2: engine.DataEngine.LoadForwardIndex:input_type -> engine.DumpMsg
	0, // 3: engine.DataEngine.LoadInvertedIndex:input_type -> engine.DumpMsg
	2, // 4: engine.DataEngine.GetForward:input_type -> engine.ForwardRequest
	4, // 5: engine.DataEngine.GetInverted:input_type -> engine.InvertedRequest
	1, // 6: engine.DataEngine.ForwardBuilder:output_type -> engine.Response
	1, // 7: engine.DataEngine.InvertedBuilder:output_type -> engine.Response
	1, // 8: engine.DataEngine.LoadForwardIndex:output_type -> engine.Response
	1, // 9: engine.DataEngine.LoadInvertedIndex:output_type -> engine.Response
	3, // 10: engine.DataEngine.GetForward:output_type -> engine.ForwardResponse
	5, // 11: engine.DataEngine.GetInverted:output_type -> engine.InvertedResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_data_engine_proto_init() }
func file_proto_data_engine_proto_init() {
	if File_proto_data_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_engine_proto_rawDesc), len(file_proto_data_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_data_engine_proto_goTypes,
		DependencyIndexes: file_proto_data_engine_proto_depIdxs,
		MessageInfos:      file_proto_data_engine_proto_msgTypes,
	}.Build()
	File_proto_data_engine_proto = out.File
	file_proto_data_engine_proto_goTypes = nil
	file_proto_data_engine_proto_depIdxs = nil
}
