// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/data_engine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataEngine_ForwardBuilder_FullMethodName    = "/engine.DataEngine/ForwardBuilder"
	DataEngine_InvertedBuilder_FullMethodName   = "/engine.DataEngine/InvertedBuilder"
	DataEngine_LoadForwardIndex_FullMethodName  = "/engine.DataEngine/LoadForwardIndex"
	DataEngine_LoadInvertedIndex_FullMethodName = "/engine.DataEngine/LoadInvertedIndex"
	DataEngine_GetForward_FullMethodName        = "/engine.DataEngine/GetForward"
	DataEngine_GetInverted_FullMethodName       = "/engine.DataEngine/GetInverted"
)

// DataEngineClient is the client API for DataEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataEngineClient interface {
	ForwardBuilder(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error)
	InvertedBuilder(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error)
	LoadForwardIndex(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error)
	LoadInvertedIndex(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error)
	GetForward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error)
	GetInverted(ctx context.Context, in *InvertedRequest, opts ...grpc.CallOption) (*InvertedResponse, error)
}

type dataEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewDataEngineClient(cc grpc.ClientConnInterface) DataEngineClient {
	return &dataEngineClient{cc}
}

func (c *dataEngineClient) ForwardBuilder(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, DataEngine_ForwardBuilder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataEngineClient) InvertedBuilder(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, DataEngine_InvertedBuilder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataEngineClient) LoadForwardIndex(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, DataEngine_LoadForwardIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataEngineClient) LoadInvertedIndex(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, DataEngine_LoadInvertedIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataEngineClient) GetForward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardResponse)
	err := c.cc.Invoke(ctx, DataEngine_GetForward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataEngineClient) GetInverted(ctx context.Context, in *InvertedRequest, opts ...grpc.CallOption) (*InvertedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvertedResponse)
	err := c.cc.Invoke(ctx, DataEngine_GetInverted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataEngineServer is the server API for DataEngine service.
// All implementations must embed UnimplementedDataEngineServer
// for forward compatibility.
type DataEngineServer interface {
	ForwardBuilder(context.Context, *DumpMsg) (*Response, error)
	InvertedBuilder(context.Context, *DumpMsg) (*Response, error)
	LoadForwardIndex(context.Context, *DumpMsg) (*Response, error)
	LoadInvertedIndex(context.Context, *DumpMsg) (*Response, error)
	GetForward(context.Context, *ForwardRequest) (*ForwardResponse, error)
	GetInverted(context.Context, *InvertedRequest) (*InvertedResponse, error)
	mustEmbedUnimplementedDataEngineServer()
}

// UnimplementedDataEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataEngineServer struct{}

func (UnimplementedDataEngineServer) ForwardBuilder(context.Context, *DumpMsg) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardBuilder not implemented")
}
func (UnimplementedDataEngineServer) InvertedBuilder(context.Context, *DumpMsg) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method InvertedBuilder not implemented")
}
func (UnimplementedDataEngineServer) LoadForwardIndex(context.Context, *DumpMsg) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadForwardIndex not implemented")
}
func (UnimplementedDataEngineServer) LoadInvertedIndex(context.Context, *DumpMsg) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadInvertedIndex not implemented")
}
func (UnimplementedDataEngineServer) GetForward(context.Context, *ForwardRequest) (*ForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetForward not implemented")
}
func (UnimplementedDataEngineServer) GetInverted(context.Context, *InvertedRequest) (*InvertedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInverted not implemented")
}
func (UnimplementedDataEngineServer) mustEmbedUnimplementedDataEngineServer() {}
func (UnimplementedDataEngineServer) testEmbeddedByValue()                    {}

// UnsafeDataEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataEngineServer will
// result in compilation errors.
type UnsafeDataEngineServer interface {
	mustEmbedUnimplementedDataEngineServer()
}

func RegisterDataEngineServer(s grpc.ServiceRegistrar, srv DataEngineServer) {
	// If the following call panics, it indicates UnimplementedDataEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataEngine_ServiceDesc, srv)
}

func _DataEngine_ForwardBuilder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataEngineServer).ForwardBuilder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataEngine_ForwardBuilder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataEngineServer).ForwardBuilder(ctx, req.(*DumpMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataEngine_InvertedBuilder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataEngineServer).InvertedBuilder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataEngine_InvertedBuilder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataEngineServer).InvertedBuilder(ctx, req.(*DumpMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataEngine_LoadForwardIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataEngineServer).LoadForwardIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataEngine_LoadForwardIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataEngineServer).LoadForwardIndex(ctx, req.(*DumpMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataEngine_LoadInvertedIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataEngineServer).LoadInvertedIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataEngine_LoadInvertedIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataEngineServer).LoadInvertedIndex(ctx, req.(*DumpMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataEngine_GetForward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataEngineServer).GetForward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataEngine_GetForward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataEngineServer).GetForward(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataEngine_GetInverted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvertedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataEngineServer).GetInverted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataEngine_GetInverted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataEngineServer).GetInverted(ctx, req.(*InvertedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataEngine_ServiceDesc is the grpc.ServiceDesc for DataEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.DataEngine",
	HandlerType: (*DataEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardBuilder",
			Handler:    _DataEngine_ForwardBuilder_Handler,
		},
		{
			MethodName: "InvertedBuilder",
			Handler:    _DataEngine_InvertedBuilder_Handler,
		},
		{
			MethodName: "LoadForwardIndex",
			Handler:    _DataEngine_LoadForwardIndex_Handler,
		},
		{
			MethodName: "LoadInvertedIndex",
			Handler:    _DataEngine_LoadInvertedIndex_Handler,
		},
		{
			MethodName: "GetForward",
			Handler:    _DataEngine_GetForward_Handler,
		},
		{
			MethodName: "GetInverted",
			Handler:    _DataEngine_GetInverted_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/data_engine.proto",
}
