// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userservice

import (
	"context"

	___pb "zerorequest/rpc/user/proto/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Response = ___pb.Response
	UserMsg  = ___pb.UserMsg

	UserService interface {
		AddUser(ctx context.Context, in *UserMsg, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) AddUser(ctx context.Context, in *UserMsg, opts ...grpc.CallOption) (*Response, error) {
	client := ___pb.NewUserServiceClient(m.cli.Conn())
	return client.AddUser(ctx, in, opts...)
}
