// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: data_engine.proto

package dataengine

import (
	"context"

	"zerorequest/rpc/engine/proto/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Condition        = pb.Condition
	DumpMsg          = pb.DumpMsg
	Filter           = pb.Filter
	ForwardRequest   = pb.ForwardRequest
	ForwardResponse  = pb.ForwardResponse
	ForwardView      = pb.ForwardView
	ForwardViewList  = pb.ForwardViewList
	InvertedRequest  = pb.InvertedRequest
	InvertedResponse = pb.InvertedResponse
	Response         = pb.Response

	DataEngine interface {
		ForwardBuilder(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error)
		InvertedBuilder(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error)
		LoadForwardIndex(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error)
		LoadInvertedIndex(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error)
		GetForward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error)
		GetInverted(ctx context.Context, in *InvertedRequest, opts ...grpc.CallOption) (*InvertedResponse, error)
	}

	defaultDataEngine struct {
		cli zrpc.Client
	}
)

func NewDataEngine(cli zrpc.Client) DataEngine {
	return &defaultDataEngine{
		cli: cli,
	}
}

func (m *defaultDataEngine) ForwardBuilder(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewDataEngineClient(m.cli.Conn())
	return client.ForwardBuilder(ctx, in, opts...)
}

func (m *defaultDataEngine) InvertedBuilder(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewDataEngineClient(m.cli.Conn())
	return client.InvertedBuilder(ctx, in, opts...)
}

func (m *defaultDataEngine) LoadForwardIndex(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewDataEngineClient(m.cli.Conn())
	return client.LoadForwardIndex(ctx, in, opts...)
}

func (m *defaultDataEngine) LoadInvertedIndex(ctx context.Context, in *DumpMsg, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewDataEngineClient(m.cli.Conn())
	return client.LoadInvertedIndex(ctx, in, opts...)
}

func (m *defaultDataEngine) GetForward(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error) {
	client := pb.NewDataEngineClient(m.cli.Conn())
	return client.GetForward(ctx, in, opts...)
}

func (m *defaultDataEngine) GetInverted(ctx context.Context, in *InvertedRequest, opts ...grpc.CallOption) (*InvertedResponse, error) {
	client := pb.NewDataEngineClient(m.cli.Conn())
	return client.GetInverted(ctx, in, opts...)
}
