// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: data_engine.proto

package server

import (
	"context"

	"zerorequest/rpc/engine/internal/logic"
	"zerorequest/rpc/engine/internal/svc"
	"zerorequest/rpc/engine/proto/pb"
)

type DataEngineServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDataEngineServer
}

func NewDataEngineServer(svcCtx *svc.ServiceContext) *DataEngineServer {
	return &DataEngineServer{
		svcCtx: svcCtx,
	}
}

func (s *DataEngineServer) ForwardBuilder(ctx context.Context, in *pb.DumpMsg) (*pb.Response, error) {
	l := logic.NewForwardBuilderLogic(ctx, s.svcCtx)
	return l.ForwardBuilder(in)
}

func (s *DataEngineServer) InvertedBuilder(ctx context.Context, in *pb.DumpMsg) (*pb.Response, error) {
	l := logic.NewInvertedBuilderLogic(ctx, s.svcCtx)
	return l.InvertedBuilder(in)
}

func (s *DataEngineServer) LoadForwardIndex(ctx context.Context, in *pb.DumpMsg) (*pb.Response, error) {
	l := logic.NewLoadForwardIndexLogic(ctx, s.svcCtx)
	return l.LoadForwardIndex(in)
}

func (s *DataEngineServer) LoadInvertedIndex(ctx context.Context, in *pb.DumpMsg) (*pb.Response, error) {
	l := logic.NewLoadInvertedIndexLogic(ctx, s.svcCtx)
	return l.LoadInvertedIndex(in)
}

func (s *DataEngineServer) GetForward(ctx context.Context, in *pb.ForwardRequest) (*pb.ForwardResponse, error) {
	l := logic.NewGetForwardLogic(ctx, s.svcCtx)
	return l.GetForward(in)
}

func (s *DataEngineServer) GetInverted(ctx context.Context, in *pb.InvertedRequest) (*pb.InvertedResponse, error) {
	l := logic.NewGetInvertedLogic(ctx, s.svcCtx)
	return l.GetInverted(in)
}
